packages:
  - "apps/*"
  - "packages/*"

overrides:
  lightningcss: "1.30.1"

allowBuilds:
  "@scarf/scarf": true
  "@swc/core": true
  esbuild: true
  lefthook: true
  sharp: true

catalog:
  "better-auth": ^1.6.23
  "@typescript/native-preview": 7.0.0-dev.20260609.1

minimumReleaseAgeExclude:
  - "@oxfmt/binding-android-arm-eabi@0.54.0"
  - "@oxfmt/binding-android-arm64@0.54.0"
  - "@oxfmt/binding-darwin-arm64@0.54.0"
  - "@oxfmt/binding-darwin-x64@0.54.0"
  - "@oxfmt/binding-freebsd-x64@0.54.0"
  - "@oxfmt/binding-linux-arm-gnueabihf@0.54.0"
  - "@oxfmt/binding-linux-arm-musleabihf@0.54.0"
  - "@oxfmt/binding-linux-arm64-gnu@0.54.0"
  - "@oxfmt/binding-linux-arm64-musl@0.54.0"
  - "@oxfmt/binding-linux-ppc64-gnu@0.54.0"
  - "@oxfmt/binding-linux-riscv64-gnu@0.54.0"
  - "@oxfmt/binding-linux-riscv64-musl@0.54.0"
  - "@oxfmt/binding-linux-s390x-gnu@0.54.0"
  - "@oxfmt/binding-linux-x64-gnu@0.54.0"
  - "@oxfmt/binding-linux-x64-musl@0.54.0"
  - "@oxfmt/binding-openharmony-arm64@0.54.0"
  - "@oxfmt/binding-win32-arm64-msvc@0.54.0"
  - "@oxfmt/binding-win32-ia32-msvc@0.54.0"
  - "@oxfmt/binding-win32-x64-msvc@0.54.0"
  - "@oxlint/binding-android-arm-eabi@1.69.0"
  - "@oxlint/binding-android-arm64@1.69.0"
  - "@oxlint/binding-darwin-arm64@1.69.0"
  - "@oxlint/binding-darwin-x64@1.69.0"
  - "@oxlint/binding-freebsd-x64@1.69.0"
  - "@oxlint/binding-linux-arm-gnueabihf@1.69.0"
  - "@oxlint/binding-linux-arm-musleabihf@1.69.0"
  - "@oxlint/binding-linux-arm64-gnu@1.69.0"
  - "@oxlint/binding-linux-arm64-musl@1.69.0"
  - "@oxlint/binding-linux-ppc64-gnu@1.69.0"
  - "@oxlint/binding-linux-riscv64-gnu@1.69.0"
  - "@oxlint/binding-linux-riscv64-musl@1.69.0"
  - "@oxlint/binding-linux-s390x-gnu@1.69.0"
  - "@oxlint/binding-linux-x64-gnu@1.69.0"
  - "@oxlint/binding-linux-x64-musl@1.69.0"
  - "@oxlint/binding-openharmony-arm64@1.69.0"
  - "@oxlint/binding-win32-arm64-msvc@1.69.0"
  - "@oxlint/binding-win32-ia32-msvc@1.69.0"
  - "@oxlint/binding-win32-x64-msvc@1.69.0"
  - oxfmt@0.54.0
  - oxlint@1.69.0
  - shadcn@4.11.0
  - ultracite@7.8.2
  - "@expo/cli@56.1.17"
  - "@expo/config-plugins@56.0.10"
  - "@expo/config-types@56.0.7"
  - "@expo/config@56.0.10"
  - "@expo/fingerprint@0.19.5"
  - "@expo/log-box@56.0.14"
  - "@expo/metro-config@56.0.15"
  - "@expo/prebuild-config@56.0.17"
  - "@expo/router-server@56.0.15"
  - babel-preset-expo@56.0.16
  - expo-asset@56.0.18
  - expo-constants@56.0.19
  - expo-modules-autolinking@56.0.17
  - expo-modules-core@56.0.18
  - expo@56.0.13
  - "@expo/ui@56.0.19"
  - expo-router@56.2.12
  - expo-splash-screen@56.0.11
